### PR TITLE
Add OCR support for scanning artifacts

### PR DESCRIPTION
**Pull request by gridhead**
Add OCR support for scanning artifacts

### CODE REVIEW

**Review by sdglitched — CHANGES_REQUESTED** [review]
Incorrect `Tool-tip` description on the `Gear` button on the new dialogue box
Screenshot from 2024-09-07 15-26-28

**Comment by sdglitched** [comment]
Multiple occurrences of `sub-stats` not populating, either `stat name` (populates with `None`) or the `stat data`
Also, most of the `Sands`, `Goblets` and `Circlets` are treated as of `Scroll of the Hero of Cinder City`

Screenshot from 2024-09-07 15-41-58
Screenshot from 2024-09-07 15-42-27

**Comment by sdglitched** [comment]
If any case if `+` appears before the `Main Stat` of the artifact it will skip fetching of `Main Stat` from text generated from ORC and will set it to default

image

**Review by sdglitched — CHANGES_REQUESTED** [review]
No `Dialogue Box` is shown when the loading of the `Tesseract OCR executable` is canceled

image

**Comment by sdglitched** [comment]
Two main issues with the current `OCR` implementation:

1. With the available trained data the text generated by the `OCR` is not **accurate** 
2. Reading artifact rarity is not possible because **`*`** is utilized to visualise the rarity by **`Genshin Impact`** rather than any form of recognizable string

**Review by sdglitched — APPROVED** [review]
This seems to be the best interpretation by the applied `OCR` unless the trained dataset is updated or another method is chosen

**Review by AvadhootDhere — APPROVED** [review]
Conditionally Approved!!

**Pull request merged**
